### PR TITLE
added couple new component categories, fixed issues with accordion

### PR DESCRIPTION
**Pull request by aaronhans**
- Changed the build process so the generated files are ignored and the git action workflow performs the install and build
- Added new elements from Konstantin's page: https://staging.covid19.ca.gov/sample/
- Added the build covid19 style file from staging as a preview dependency because it is required for these bootstrap dependent components
- Fixed broken accordion

### CODE REVIEW

**Review by chachasikes — APPROVED** [review]
Cool! Thanks for adding the build action.

**Comment by chachasikes** [comment]
Not sure why the build check fails though

**Review by chachasikes — COMMENTED** [review]
Not sure if I can unapprove, but will note some issues running the build here:

ERROR in ./stories/covid19-site/ArrowLink/ArrowLink.js
Module not found: Error: Can't resolve '@cagov/arrow' in ...`/storybook-ca-gov/stories/covid19-site/ArrowLink'

**Comment by aaronhans** [comment]
using gitpkg to install that isn't behaving, I'll fix it

**Comment by aaronhans** [comment]
build issues fixed now

**Pull request merged**
